### ISSUE TITLE
[Feature Request] SendMessage-Callback-API

### ISSUE THREAD

**Issue by proepkes** [DarkRiftNetworking/DarkRift-Networking#11]
### Quick Description
SendMessage-Callback-API: 
client.SendMessage(Tag, Message, SendMode, (onResponse) => { ... switch(onResponse.Status) ...});
OR
client.SendMessage(MyTag, MyMessage, MySendMode, (onSuccess, onError) => { ... });

### Explanation
Instead of handling responses in the MessageReceived-Event, this feature leads to a cleaner and easy-to-read response-handling. The SendMessage gets a delegate which handles the response to the corresponding message. Because two callbacks "onSuccess" and "onError" can be application-specific (I guess?) there is another option of "onResponse" which contains a status-enumerable.

The status should contain at least:
Success,
Error,
Timeout  <-- default timeout configured in Server.config

Sending a response:
public void HandleClientRequest(Message message)
{
  //Check message
  message.Respond(ResponseStatus.Success, myIDarkRiftSerializable)
}

**Comment by JamJar00** [comment]
This looks like a fairly big change and would require the introduction of message identifiers in order to respond to the correct messages. It seems like a big change from DarkRift's fire-and-forget sort of style (being more rest like if I understand correctly) but could be something for the future. I'll have a think into how it could be done easily!

I'd be interested to hear others' opinions on this.

Thanks!

**Comment by NixAJ** [comment]
I think this feature is one of those where it is more of a quality of life enhancement rather than a missing feature... I suppose an upgrade to what darkrift has now.

For my sake, I dont mind using either, but its definently an interesting approach compared to currently, however this also means more overhead on messages, which could become an issue with bigger games.
