### ISSUE TITLE
Access to byte arrays of Readers/Writers

### ISSUE THREAD

**Issue by Lukeesta** [DarkRiftNetworking/DarkRift-Networking#38]
Sometimes it would be nice to have access to the byte arrays of DarkriftWriters and Readers to copy or manipulate them. At the moment they are not accesible, id it has no technical reasons to hide them then it would be nice if we could access them.

**Comment by JamJar00** [comment]
Hi Lukeesta,

I'll look into exposing these for you. There are some possible problems as the arrays are pre-padded to allow for header information to be added and will at some point be recycled so it might not be as simple as you think unfortunately!

Jamie

**Comment by JamJar00** [comment]
Hey Lukeesta, 

I've looked into this and don't think it's going to be possible. Unfortunately because the writers dynamically expand, if you were to copy a reference to the array and then add to the writer the array may be resized and you'd find your reference was no longer correct. I can't see any way around that so I suggest if there's any array methods you like to be able to use on DarkRiftWriters just create new issues and I can add them to the writer directly so that it handle's the resizing correctly!

Jamie
