### ISSUE TITLE
Plugins do not load in .NET Core

### ISSUE THREAD

**Issue by Reousa** [DarkRiftNetworking/DarkRift-Networking#47]
### Quick Description
.Net core console app fails to load plugins if they reference other dlls.

### Explanation
The .NET Core console app will *only* load plugins that reference DLLs if it *also* references those DLLs and has loaded them when started.

It's worth mentioning that this *only* happens when building against .NET Core & it does *not* happen in .NET Framework builds of the server.

#### Fails to load
> Create an empty Plugin `X` that references DLL `Y`.
> Place `X` & `Y` in `/Plugins`
> Run console app.

#### Loads successfully
> Create an empty Plugin `X` that references DLL `Y`.
> Have the console app also reference DLL `Y`.
> Place `X` in `/Plugins`
> Place `Y` in `/Lib`
> Run console app.

### Info
This might just be a .NET Core issue unrelated to DR2, I have not done further research.

**Comment by arnoau** [comment]
I also came across this issue, sorry I should have raised it earlier.

Using Assembly.LoadFrom instead of Assembly.LoadFile in the PluginFactory allows .NET Core to load plugins which reference other custom libraries correctly.

Here is some info on why this is the case: [LoadFile vs. LoadFrom](https://blogs.msdn.microsoft.com/suzcook/2003/09/19/loadfile-vs-loadfrom/)

**Fix:**

DarkRift.Server\PluginFactory.cs: 116
```cs
112:            //Load the assembly
113:            Assembly assembly;
114:            try
115:            {
116:                //assembly = Assembly.LoadFile(Path.GetFullPath(file));
117:                assembly = Assembly.LoadFrom(Path.GetFullPath(file));
118:            }
```

**Comment by JamJar00** [comment]
Good find! I had no idea about those differences so that would've taken me a good while to find aha! Thanks 🙂

**Comment by JamJar00** [comment]
I've applied the fix to the next version 🙂
